version: '2'
services:
  codeceptjs:
    image: codeceptjs/codeceptjs
    depends_on:
      - chromium
    volumes:
      - .:/tests
  chromium:
    image: playwright/chromium
    ports:
      - '4444:4444'
      - '5900:5900'