version: '2'
services:
  codeceptjs:
    image: codeceptjs/codeceptjs
    depends_on:
      - firefox
    volumes:
      - .:/tests
  firefox:
    image: selenium/standalone-firefox-debug:2.53.0
    # image: selenium/standalone-chrome-debug
    # image: playwright/chromium
    ports:
      - '4444'
      - '5900'