version: '2'
services:
  codeceptjs:
    image: codeceptjs/codeceptjs
    depends_on:
      - chromium
    volumes:
      - .:/tests
  chromium:
    # image: selenium/standalone-firefox:4.6.0-20221104
    image: playwright/chromium
    ports:
      - '4444:4444'
      - '5900:5900'